app:
  build: ./docker/go
  dockerfile: Dockerfile-Go
  container_name: goapi
  tty: true
  volumes:
    - ./app:/go/src/github.com/bryutus/caspian-serverside/app
  ports:
    - 1323:1323
  links:
    - db
db:
  build: ./docker/mysql
  dockerfile: Dockerfile-MySQL
  container_name: mysql
  volumes:
    - ./docker/mysql/data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=app
  command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci
